title: Mi sitio web sencillo
description: PÃ¡gina creada con Jekyll y GitHub Pages
# remote_theme: mmistakes/minimal-mistakes@4.33.0
remote_theme: mmistakes/minimal-mistakes@4.27.3
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

header_pages:
  - index.md
  - about.md
  - contact.md

minimal_mistakes_skin    : "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
